### ISSUE TITLE
Constants *can* be GC'd

### ISSUE THREAD

**Issue by tenderlove** [benoittgt/understand_ruby_gc#2]
If you remove a constant, the object it points to will be GC'd.  But constants aren't really a type of object, it's just a name.

**Comment by benoittgt** [comment]
Yes you're correct. I was *blurred* by 

> The most obvious way that Ruby grows in memory usage is by retaining objects. Constants in Ruby are never garbage collected so if a constant has a reference to an object, then that object can never be garbage collected. [source](https://www.sitepoint.com/ruby-uses-memory/)

Readme changed with https://github.com/benoittgt/understand_ruby_memory/pull/3
